### ISSUE TITLE
cronjob like behaviour of the nextflow workflow is sub-optimal for some applications

### ISSUE THREAD

**Issue by mwalzer** [elixir-cloud-proteomics-workflows/elixir_proteomics_QC#4]
I think the workflow when started as instructed goes in scan-for-input-files mode without a clear end-state? It might be better for some applications like project/submission based file sets to have a simple workflow that takes a predefined input and does its thing. Is it possible to make switch between these behaviours with a nextflow command line flag or something else?

**Comment by lucacozzuto** [comment]
done
