### ISSUE TITLE
Workflow param settings do not take hold

### ISSUE THREAD

**Issue by mwalzer** [elixir-cloud-proteomics-workflows/elixir_proteomics_QC#5]
So I created a folder `raw` with some raw file zips and a file `params.config` that contains `zipfiles         = "$baseDir/raw/*.zip"` in the same folder in which the nextflow workflow file is located. 
I deactivated the `queue` config to get to default submission queue. What am I missing? I get this:
```
[walzer@hh-yoda-04-12 test]$ N E X T F L O W  ~  version 19.04.1
Launching `elixir_proteomics_QC.nf` [naughty_shaw] - revision: 3e6800450e
WARN: Access to undefined parameter `zipfiles` -- Initialise it to a default value eg. `params.zipfiles = some_value`
WARN: Access to undefined parameter `qconfig` -- Initialise it to a default value eg. `params.qconfig = some_value`
WARN: Access to undefined parameter `fasta_tab` -- Initialise it to a default value eg. `params.fasta_tab = some_value`
WARN: Access to undefined parameter `out_folder` -- Initialise it to a default value eg. `params.out_folder = some_value`
WARN: Access to undefined parameter `email` -- Initialise it to a default value eg. `params.email = some_value`
elixir_proteomics_QC - N F  ~  version 0.1
========================================
┌─┐┬  ┬─┐ ┬┬┬─┐    ┌─┐┬─┐┌─┐┌┬┐┌─┐┌─┐┌┬┐┬┌─┐┌─┐    ╔═╗ ╔═╗
├┤ │  │┌┴┬┘│├┬┘    ├─┘├┬┘│ │ │ ├┤ │ ││││││  └─┐    ║═╬╗║  
└─┘┴─┘┴┴ └─┴┴└─────┴  ┴└─└─┘ ┴ └─┘└─┘┴ ┴┴└─┘└─┘────╚═╝╚╚═╝

========================================
zipfiles (input files)            : null
qconfig (config file)             : null
fasta_tab (tsv file)              : null
out_folder (output folder)        : null
email for notification            : null

ERROR ~ Argument of `file` function cannot be null
```

BTW, it is a _very_ good idea to have included the param settings review at the start prompt :+1:

**Comment by lucacozzuto** [comment]
the file params need to be in the same folder of nextflow pipeline. Or you can pass the parameters via command line like:
nextflow run main.nf --zipfiles "myfiles/*.zip" etc.

**Comment by mwalzer** [comment]
Yes, both params.config and the input folder are in the same folder which also contains the nextflow

**Comment by lucacozzuto** [comment]
The pipeline reads the nextflow.config file. This in the first line has an include of the params file
```
includeConfig "$baseDir/params.config"
```
so if the params.config is not found it complains... Can you check that everything is in the right place?

**Comment by rolivella** [comment]
@mwalzer was this issue solved?
