### ISSUE TITLE
Move RawFileReader outside the docker container

### ISSUE THREAD

**Issue by rolivella** [elixir-cloud-proteomics-workflows/elixir_proteomics_QC#6]
Just to reminder that before publishing the official QC pipeline we would suggest to move the Thermo RawFileReader from the docker container to an external folder (to "bin", for instance).  

What do you think?

**Comment by mwalzer** [comment]
Do you mean a singularity image in the folder? I am not sure if it would be easy to have the reader version working outside a container environment. I'd prefer to move to an official release (https://github.com/elixir-cloud-proteomics-workflows/elixir_proteomics_QC/blob/4c79a5e6d8f437016e8c83aed9390e57935ba194/nextflow.config#L16) 
@nielshulstaert does each release come with a container version? In which increments should we pick and update versions of our dependency you suggest?.

**Comment by lucacozzuto** [comment]
No, we will call the binary from the image using the NF built-in function. In brief the image will be without the binary that must be downloaded by the user and placed inside the bin folder in the pipeline. This is to avoid the licensing problems...

**Comment by mwalzer** [comment]
with a container version from say https://quay.io/repository/biocontainers/thermorawfileparser?tag=latest&tab=tags this would also circumvent?

**Comment by lucacozzuto** [comment]
So I  don't get it... if this program is inside a biocontainer the license should be not restricitive...

**Comment by rolivella** [comment]
@mwalzer and @lucacozzuto I would suggest to follow the way this package (which has been peer-reviewed) solved the same situation: 

https://github.com/fgcz/rawDiag

> Due to licensing reasons, we currently not allowed to distribute Thermo Fisher Scientific software with the rawDiag package (we hope that this will change soon). The New RawFileReader from Thermo Fisher Scientific has to be downloaded and installed separately in order to be able to directly read Thermo raw-files (by using the R function read.raw).

Of course adapted to our folder structure, i.e. the /bin folder as @lucacozzuto suggested.

**Comment by lucacozzuto** [comment]
It has to be tested anyway. We had similar issued with some Oxford Nanopore's basecallers... We solved by giving the instructions on how to install them in our pipeline

https://github.com/biocorecrg/master_of_pores
